import Head from "next/head";
import styles from "../styles/Home.module.css";

export async function getServerSideProps(context) {
  let res = await fetch("http://localhost:3000/api/products", {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
    },
  });
  let food = await res.json();
  return {
    props: { food },
  };
}

export default function Home(props) {
  console.log(props.food.food, "props in home");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {props?.food.food.map((food) => {
          return food.food.map((data) => {
            return (
              <article key={data.id}>
                <h3>{data.name}</h3>
                <p>quantity: {data.quantity}</p>
              </article>
            );
          });
        })}
      </main>
    </div>
  );
}
